include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_redundant_argument_values: false
    unnecessary_string_interpolations: true
    always_declare_return_types: true
    unawaited_futures: true
